### ISSUE TITLE
Restrict harmful Replication Factor (RF) values

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/scylladb#14207]
First we need to decide:

1. what values are considered harmful, i.e. which ones we do allow for users to set without issuing a warning/dropping a query.
2. if we issue a warning or drop a query when a "harmful" RF value was requested.
```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylladb/issues/8619
- [ ] https://github.com/scylladb/scylladb/issues/8892
- [ ] https://github.com/scylladb/scylladb/issues/8891
```

**Comment by ptrsmrn** [comment]
@nyh We decided to issue a warning for scylla OSS and enterprise if the RF is lower than 3, but the restriction that we've implemented - https://github.com/scylladb/scylladb/pull/9830 - doesn't allow for a warning, it is only able to produce an error, so we either go with an error (unlikely) or we need to extend this restriction to handle warnings (likely). If we want to extend it, the question is whether to just allow for enabling warnings for this restriction or to substitute this restriction with a "guardrail", as Cassandra did - https://github.com/apache/cassandra/pull/1583/files#diff-77707d0908c31940828b6425dcb09a7409827db99b48c371f71c63294dfe1562R1689. Regarding substituting, I'm aware that we don't have the full picture of who's using `minimum_keyspace_rf` (my guess is that anyone), but at least I don't expect the process of moving from `minimum_keyspace_rf` guardrail to e.g. `minimum_replication_factor_fail_threshold` to be hard. AFAIK we don't substitute config files, `scylla.yaml`, in case of enterprise upgrades, so (perhaps) in the worst case we'd only disable this limit, and in the average case, after manually updating the config file, the new warn limit would be in place.
I'll try to to collect some feedback to see if anyone has `minimum_keyspace_rf` config option set.

**Comment by ptrsmrn** [comment]
> > If we want to extend it, the question is whether to just allow for enabling warnings for this restriction or to substitute this restriction with a "guardrail", as Cassandra did - https://github.com/apache/cassandra/pull/1583/files#diff-77707d0908c31940828b6425dcb09a7409827db99b48c371f71c63294dfe1562R1689.
> 
> I agree, the "easiest" solution (design-wise) will be to copy what Cassandra did, and be done with that.
> 
> That being said, I think Cassandra's interface makes little sense. Why would anybody want to set the "sort" and "hard limit separately? E.g., to warn if RF<3 but error if RF<2? My guess is that users will only want to have a single number in mind (e.g., 3) and then decide if this number should be a warning or an error. Still, even if Cassandra's configuration makes little sense to me, it doesn't mean we shouldn't copy it.

Having both the soft and the hard limits is a general Cassandra's design, for RF it doesn't have to make as much sense as for other options, e.g. ReplicationStrategy, where we could first issue a warning for SimpleStrategy, making it deprecated, and in the following release by default forbid to use it, making it obsoleted. Or first warn about and then prevent to write to huge partitions. But even for RF it could make sense to warn if e.g RF>3 or error out when RF>10 - of course these are upper, not lower RF limits.

**Comment by nyh** [comment]
> Having both the soft and the hard limits is a general Cassandra's design, for RF it doesn't have to make as much sense as for other options, e.g. ReplicationStrategy, where we could first issue a warning for SimpleStrategy, making it deprecated, and in the following release by default forbid to use it, making it obsoleted.

The replication strategy example just shows how silly is Cassandra's option design where everything is a numeric "soft" and "hard" limit... In this example, you don't even have numeric values for the different strategies. How did they even do it?

**Comment by ptrsmrn** [comment]
@eliransin provided me cloud config files, and there're no mentions of `minimum_keyspace_rf` whatsoever, so at least cloud is covered. Enterprise remains an open question, though I strongly believe it's also not used there.
BTW. grepping for `restrict_` also returns nothing, and we have have `restrict_replication_simplestrategy` config param in the source code.

**Comment by gcarmin** [comment]
We must have a way for our support and SA to overcome that. we already have some existing customers and prospect that uses RF><3 and we should have a way to do so per requirement

**Comment by ptrsmrn** [comment]
> We must have a way for our support and SA to overcome that. we already have some existing customers and prospect that uses RF><3 and we should have a way to do so per requirement

@tzach does that statement change how we want to control guardrails' settings or scylla.yaml is still enough? (Modifying guardrails via CQL will not be possible).
