### ISSUE TITLE
hinted handoff: Refactor the module

### ISSUE THREAD

**Issue by dawmd** [scylladb/scylladb#15358]
## Context and motivation
Hinted Handoff was implemented in Scylla a few years ago. Over the years, people have modified the module, but no significant changes have been made in its design or logic. Changes have been made nonetheless – for example, `db/hints/manager.cc` has grown from barely 800 lines to more than 1400. This file (along with the corresponding header) is the part we shall focus on here as it plays the key role in Hinted Handoff.

As of now, the files suffer from technology debt that has accumulated throughout this time; among the problems are: no clear set of functionalities the files should implement, good amounts of old code, (arguably) overly compact coding style, and no clear ownership/responsibility of data structures. The most serious issue is, however, reliance on "hacky" solutions (e.g. recreating commitlog instances to be able to send hints), which combined with previously mentioned problems makes the code extremely difficult to understand despite many good comments and the design of Hinted Handoff described thoroughly in the documentation.

Hinted Handoff may and will change sooner or later, possibly growing even bigger and becoming more complex. It is therefore crucial to address said issues possibly soon.

### Modularization
The most important step to take is to modularize `manager.hh` by dividing it into several smaller files, each with a clear purpose. I propose the following structure:

* `hint_storage`: all logic related to storing hints on disk, most notably: isolating commitlog from the rest of the code, abstracting out browsing, creating and deleting hint files, rebalancing them at start-up
* `hint_sender`: sending hints to hosts and interaction with the API wrapping commitlog from `hint_storage` – reading hints from disk, reporting that a hint has been successfully sent, etc.
* `hint_host_manager`: managing hints for a specific host: creating instances of data structures defined in `hint_storage` and communicating with them to store hints; creating a `hint_sender` instance and managing it
* `shard_hint_manager`: creating instances of `hint_host_manager` and managing them; functioning as the API for the user of the API (the rest of the listed files should only be used internally).

This will not only isolate internal logic of the module, but it will also provide a more organized structure and dependency chain, as well as make reasoning about the control flow and the logic easier.

### Code clean-up
C++20 has brought many useful features, the most prominent in the context of Scylla is definitely coroutines. Currently, Hinted Handoff uses very long continuations, which force the developer to use multiple nested lambdas and pass their captures. That not only makes the code compact to the point it's hard to read at some places, but it also gives a lot of room for error, e.g. forget to capture a shared pointer and your code will break, but you might only learn it in debug mode. Or not at all.

Coroutines can be used to solve this. Though they introduce new non-trivial problems (e.g. the infamous [lamda corotuine fiasco](https://github.com/scylladb/seastar/blob/master/doc/lambda-coroutine-fiasco.md)), in most cases they lead to simpler, more readable code, easier to maintain and reason about.

Smaller changes, like changing formatting or reordering functions in files, can also have positive impact on the module.

All files should be read, analyzed and refactored accordingly.

## Plan of work
I propose the following plan of work. Each task should correspond to one PR

```[tasklist]
### Tasks
- [ ] Divide `manager.{hh, cc}` into smaller files as listed in **Solution.Modularization**, but preserving the current implementation of the data structures and their relation. Ignore `hint_storage` at this stage. Rename the data structures to match the names from this issue (though the renaming part can be skipped of course).
- [ ] Move the logic related to rebalancing hint files to `hint_storage` from `manager`.
- [ ] Clean up `hint_storage`.
- [ ] Clean up `hint_sender`.
- [ ] Clean up `hint_host_manager`.
- [ ] Clean up `shard_hint_manager`.
- [ ] Clean up `resource_manager`.
- [ ] Clean up `host_filter`.
- [ ] Implement wrappers over commitlog in `hint_storage` and make the other parts of the code use it.
```

**Comment by kostja** [comment]
@dawmd do you want to continue with this?

**Comment by dawmd** [comment]
> @dawmd do you want to continue with this?

Yes, as long as there aren't more important items
