### ISSUE TITLE
add a switch in `configure.py` to use CMake building system

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#15379]
the switch should use CMake to generate the building system instead its own to generate a top-level `build.ninja`. which can in turn call into the `build.ninja` created by CMake

```[tasklist]
### task list
- [ ] either use lower-case build mode or fix `isScylla` in `ccmlib/common.py`, so it (also) checks for executable like `build/Debug/scylla`
- [ ] add the multi-config support to Seastar
- [x] add the multi-config support to scylla
- [ ] check the targets used by jenkins, and implement them if missing
- [ ] add the switch. see #15916 for the previous attempt
```
