### ISSUE TITLE
raft topology: followups to cluster features/join node RPC PR

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#15555]
This issue is about implementing followups that were mentioned in review of https://github.com/scylladb/scylladb/pull/15196:

Major items:

- Adjust the procedure not to use timeouts when the joining node is waiting for the coordinator to respond to it; the topology coordinator might not process the request for a long time (e.g. if tablet migrations are in progress or several other nodes are trying to join). Ref: https://github.com/scylladb/scylladb/issues/15600#issuecomment-1744849348

Minor items:

- Don't register any of the raft topology RPC verbs if raft topology is disabled, not only the join_node related (https://github.com/scylladb/scylladb/pull/15196#discussion_r1338149933)
- ~Remove unused headers in storage_service~ (https://github.com/scylladb/scylladb/pull/15196#discussion_r1338144880) (will be covered by #15196)
- Handle rejection of new nodes outside topology state machine / do it like we tell nodes to shut down in `node_state::left_token_ring` (https://github.com/scylladb/scylladb/pull/15196#discussion_r1336923262)
- Check that the replaced node is dead when replacing it through topology coordinator (https://github.com/scylladb/scylladb/pull/15196#discussion_r1336912430)
- ~Simplify handling timeouts in `join_node_request` handler (https://github.com/scylladb/scylladb/pull/15196#discussion_r1336800639)~ (made obsolete by the next point)
- Improve the workaround for replacing a node very quickly, or think about a more proper solution (https://github.com/scylladb/scylladb/pull/15196#discussion_r1335885311, https://github.com/scylladb/scylladb/pull/15196#discussion_r1335880662)
- Make sure to start group0 first, before the topology coordinator adds the new node to configuration
- Insert bootstrap tokens only after the new node performs a read barrier and reads the newest schema (https://github.com/scylladb/scylladb/issues/15686#issuecomment-1755608750)

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylladb/issues/15853
- [ ] https://github.com/scylladb/scylladb/issues/15738
- [ ] https://github.com/scylladb/scylladb/issues/15862
- [ ] https://github.com/scylladb/scylladb/issues/15863
- [ ] https://github.com/scylladb/scylladb/issues/15865
- [ ] https://github.com/scylladb/scylladb/issues/15866
- [ ] https://github.com/scylladb/scylladb/issues/15935
- [ ] https://github.com/scylladb/scylladb/issues/15686
```

**Comment by kbr-scylla** [comment]
cc @gleb-cloudius

**Comment by piodul** [comment]
There is one more issue with the handshake in its current form (https://github.com/scylladb/scylladb/compare/master...piodul:scylla:older-join-node-rpc). Now, it might happen that the topology coordinator adds the new node to group 0 quicker than the new node starts its group 0 server. More specifically, we would like to have the following order of events:

```
1. Joining node sends request to join
2. Joining node gets approval and confirmation about placing the request
3. Joining node starts group 0 server
4. Topology coordinator adds joining node to group 0 configuration
5. Topology coordinator accepts and sends response
6. Joining node performs read barrier to save the features and enable them
7. Joining node finishes the response rpc and unblocks the coordinator
```

... but nothing prevents 3 from happening after 4 or later. I applied a quick fix to the PR so that the join_node_response handler (step 5) waits until the group 0 is started (step 3 finishes), but if 4 happens before 3 then we might get some ugly (but non-critical) messages:

```
INFO  2023-09-27 15:42:42,611 [shard 0:stat] rpc - client 127.0.0.1:56352 msg_id 2:  exception "Raft group b8542540-5d3b-11ee-99b8-1052801f2975 not found" in no_wait handler ignored
INFO  2023-09-27 15:42:42,710 [shard 0:stat] rpc - client 127.0.0.1:56352 msg_id 3:  exception "Raft group b8542540-5d3b-11ee-99b8-1052801f2975 not found" in no_wait handler ignored
```

One option to prevent that would be to start group 0 server as the first step, and add a persistent flag that tells us whether the previous upgrade didn't complete yet. We would check in a "zeroth" step and fail the boot if it was set, instead of relying on join_node_request to tell us whether it's ok to join or not.

We need to have access to group 0 in join_node_response handler because we want to perform a group0 barrier there to fetch the `enabled_features` column and wait for normal nodes to appear alive in gossip.

@gleb-cloudius @kbr-scylla Do you see other solutions than the one with the flag?

**Comment by gleb-cloudius** [comment]
> 
> @gleb-cloudius @kbr-scylla Do you see other solutions than the one with the flag?

Since `hots_id` and raft server id are the same we do not need to access group0 in `handle_raft_rpc` to check the id, so what we can do there is to check `host_id` and if it matches wait for group0 to appear.

**Comment by piodul** [comment]
Added one more item to the list:

> - Adjust the procedure not to use timeouts when the joining node is waiting for the coordinator to respond to it; the topology coordinator might not process the request for a long time (e.g. if tablet migrations are in progress or several other nodes are trying to join). Ref: https://github.com/scylladb/scylladb/issues/15600#issuecomment-1744849348

**Comment by kbr-scylla** [comment]
Added new item to the tasklist:
https://github.com/scylladb/scylladb/issues/15935

**Comment by kbr-scylla** [comment]
The only remaining task is https://github.com/scylladb/scylladb/issues/15866, closing this issue as it's redundant.
