### ISSUE TITLE
Scylla-native repacement for nodetool

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#15588]
This umbrella issue tracks the effort to re-implement nodetool as a scylla-native tool.
The effort was started by this PR: https://github.com/scylladb/scylladb/pull/14841.

Below is s table of all nodetool commands and the state of their reimplementation:
```[tasklist]
### Tasks
- [x] cfhistograms/tablethistograms - https://github.com/scylladb/scylladb/pull/17651
- [x] cfstats/tablestats - https://github.com/scylladb/scylladb/pull/17387
- [x] cleanup - https://github.com/scylladb/scylladb/pull/15843
- [x] clearsnapshot - https://github.com/scylladb/scylladb/pull/15843
- [x] compactionhistory - https://github.com/scylladb/scylladb/pull/15649
- [x] compactionstats - https://github.com/scylladb/scylladb/pull/17344
- [x] compact - https://github.com/scylladb/scylladb/pull/14841
- [x] decommission - https://github.com/scylladb/scylladb/pull/16348
- [x] describecluster - https://github.com/scylladb/scylladb/pull/17240
- [x] describering - https://github.com/scylladb/scylladb/pull/17163
- [x] disableautocompaction - https://github.com/scylladb/scylladb/pull/15939
- [x] disablebackup - https://github.com/scylladb/scylladb/pull/15593
- [x] disablebinary - https://github.com/scylladb/scylladb/pull/15593
- [x] disablegossip - https://github.com/scylladb/scylladb/pull/15593
- [x] drain - https://github.com/scylladb/scylladb/pull/15939
- [x] enableautocompaction - https://github.com/scylladb/scylladb/pull/15939
- [x] enablebackup - https://github.com/scylladb/scylladb/pull/15593
- [x] enablebinary - https://github.com/scylladb/scylladb/pull/15593
- [x] enablegossip - https://github.com/scylladb/scylladb/pull/15593
- [x] flush - https://github.com/scylladb/scylladb/pull/15939
- [x] getendpoints - https://github.com/scylladb/scylladb/pull/17332
- [x] getlogginglevels - https://github.com/scylladb/scylladb/pull/16348
- [x] gettraceprobability - https://github.com/scylladb/scylladb/pull/15593
- [x] gossipinfo - https://github.com/scylladb/scylladb/pull/17317
- [x] help - https://github.com/scylladb/scylladb/pull/15593
- [x] info - https://github.com/scylladb/scylladb/pull/17498
- [x] listsnapshots - https://github.com/scylladb/scylladb/pull/15843
- [x] move - https://github.com/scylladb/scylladb/pull/16348
- [x] netstats -https://github.com/scylladb/scylladb/pull/17651
- [x] proxyhistograms -https://github.com/scylladb/scylladb/pull/17651
- [x] rebuild - https://github.com/scylladb/scylladb/pull/16348
- [x] refresh - https://github.com/scylladb/scylladb/pull/16348
- [x] removenode - https://github.com/scylladb/scylladb/pull/16348
- [x] repair - https://github.com/scylladb/scylladb/pull/17368
- [x] ring - https://github.com/scylladb/scylladb/pull/17375
- [x] scrub - https://github.com/scylladb/scylladb/pull/16391
- [x] setlogginglevel - https://github.com/scylladb/scylladb/pull/16348
- [x] settraceprobability - https://github.com/scylladb/scylladb/pull/15593
- [x] snapshot - https://github.com/scylladb/scylladb/pull/15939
- [x] statusbackup - https://github.com/scylladb/scylladb/pull/15593
- [x] statusbinary - https://github.com/scylladb/scylladb/pull/15593
- [x] statusgossip - https://github.com/scylladb/scylladb/pull/15593
- [x] status- https://github.com/scylladb/scylladb/pull/17547
- [x] stop - https://github.com/scylladb/scylladb/pull/15649
- [x] toppartitions - https://github.com/scylladb/scylladb/pull/17357
- [x] upgradesstables -https://github.com/scylladb/scylladb/pull/17370
- [x] viewbuildstatus - https://github.com/scylladb/scylladb/pull/17344
- [x] version - https://github.com/scylladb/scylladb/pull/15593
```

List of commands is from https://opensource.docs.scylladb.com/stable/operating-scylla/nodetool.html.

**Comment by denesb** [comment]
The following script can be used to snoop on what nodetool is doing:
```python
#!/usr/bin/env python3

import subprocess
import sys
import time

NODETOOL_PATH = \
        '/home/bdenes/ScyllaDB/scylla/worktree4/tools/java/bin/nodetool'

tshark = subprocess.Popen(
        ['tshark', '-i', 'lo', '-w', 'out.pcapng', '-F', 'pcapng', '-q'],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True)

for line in tshark.stderr:
    print(f"tshark> {line.rstrip()}")
    if "Capture started" in line:
        break

# For some reason, even after printing "Capture started", tshark can miss
# packets sent immediately after, this sleep here seems to ensure they are all
# captured.
time.sleep(1)

try:
    with subprocess.Popen([NODETOOL_PATH] + sys.argv[1:], text=True,
                          stdout=subprocess.PIPE) as proc:
        for line in proc.stdout:
            print(f"nodetool> {line.rstrip()}")
finally:
    tshark.terminate()
    tshark.wait()
    for line in tshark.stderr:
        print(f"tshark> {line.rstrip()}")
```

Unfortunately it is not 100% reliable. Requests sent by very quick commands are sometimes not captured. Not sure why.

**Comment by mykaul** [comment]
I think we need an item (or more) on removal of the Java native tooling

**Comment by denesb** [comment]
> I think we need an item (or more) on removal of the Java native tooling

We have https://github.com/scylladb/scylladb/issues/14856.

**Comment by amnonh** [comment]
> The following script can be used to snoop on what nodetool is doing:
> 

It's a two line of code to change the scylla-jmx to print the request url, I suggest modify scylla-jmx and run it excplicitely instead of as a service.

**Comment by denesb** [comment]
> > The following script can be used to snoop on what nodetool is doing:
> 
> It's a two line of code to change the scylla-jmx to print the request url, I suggest modify scylla-jmx and run it excplicitely instead of as a service.

Good to know. I already run `scylla-jmx` explicitely.

**Comment by tchaikov** [comment]
@denesb could you link the corresponding item in the task list to #17240 ?

**Comment by denesb** [comment]
> @denesb could you link the corresponding item in the task list to #17240 ?

Done.

**Comment by tchaikov** [comment]
@denesb could you link the corresponding item in the task list to #17317 ?

**Comment by denesb** [comment]
> @denesb could you link the corresponding item in the task list to #17317 ?

Done.

**Comment by tchaikov** [comment]
@denesb could you link the corresponding item in the task list to #17332 ?

**Comment by denesb** [comment]
> @denesb could you link the corresponding item in the task list to #17332 ?

Done.

**Comment by tchaikov** [comment]
@denesb FWIW, to avoid the potential conflicts, i am working on `compactionstats`.

**Comment by tchaikov** [comment]
@denesb could you link the corresponding item in the task list to #17344?

**Comment by denesb** [comment]
> @denesb could you link the corresponding item in the task list to #17344?

Done.

**Comment by tchaikov** [comment]
> @denesb could you link the corresponding item in the task list to #17344?

@denesb thank you Botond! because  the implementation of `viewbuildstatus` depends on part of `compactionstats`, it is also included in this PR. could you please link `viewbuildstatus` to this PR as well?

**Comment by denesb** [comment]
> > @denesb could you link the corresponding item in the task list to #17344?
> 
> @denesb thank you Botond! because the implementation of `viewbuildstatus` depends on part of `compactionstats`, it is also included in this PR. could you please link `viewbuildstatus` to this PR as well?

Done and thanks for the help. We are almost down to 10 commands to be implemented.

**Comment by mykaul** [comment]
> > > @denesb could you link the corresponding item in the task list to #17344?
> > 
> > 
> > @denesb thank you Botond! because the implementation of `viewbuildstatus` depends on part of `compactionstats`, it is also included in this PR. could you please link `viewbuildstatus` to this PR as well?
> 
> Done and thanks for the help. We are almost down to 10 commands to be implemented.

Sounds like we have a real chance to squeeze it in to 6.0.
(in which case, I'll ask to split cassandra-stress from our tools to a different package, and we'll get rid of Java in our base packages!)

**Comment by horschi** [comment]
@mykaul : As a user I also think scylla should have no java dependency. Also I don't think a stress tool should be part of the installation on my production servers.

**Comment by denesb** [comment]
@tchaikov if we think there is a chance that we can squeeze this into 6.0, then we should not invest into `tools/java/bin/nodetool-wrapper`, because we will just replace it with `scylla-nodetool` instead.
From my end, I will resume working on `nodetool repair` command.

**Comment by tchaikov** [comment]
FWIW, i am working on `toppartitions`.

**Comment by tchaikov** [comment]
> @tchaikov if we think there is a chance that we can squeeze this into 6.0, then we should not invest into `tools/java/bin/nodetool-wrapper`, because we will just replace it with `scylla-nodetool` instead. From my end, I will resume working on `nodetool repair` command.

yeah, this was exactly why i started working on this front.  `nodetool-wrapper` is pending on the [discussion](https://github.com/scylladb/scylla-tools-java/pull/380). so i evaluated the outcome of the discussion and the workload of implementing scylla-nodetool couple days ago, and decided to spend my time on the latter.

**Comment by tchaikov** [comment]
@denesb could you link the corresponding item in the task list to #17357?

**Comment by denesb** [comment]
> @denesb could you link the corresponding item in the task list to #17357?

Done.

**Comment by tchaikov** [comment]
while looking at "ring" subcommand. shall we have a corresponding command for printing the tablets mapping? like `tablets` ?

**Comment by tchaikov** [comment]
FWIW, i am working on `ring`.

**Comment by denesb** [comment]
> while looking at "ring" subcommand. shall we have a corresponding command for printing the tablets mapping? like `tablets` ?

Right, indeed this command is intricately linked to vnodes. Maybe we can add a tablets command later (although one can just query `system.tablets` already), but for now we should focus on converting the existing commands.

**Comment by tchaikov** [comment]
> > while looking at "ring" subcommand. shall we have a corresponding command for printing the tablets mapping? like `tablets` ?
> 
> Right, indeed this command is intricately linked to vnodes. Maybe we can add a tablets command later (although one can just query `system.tablets` already), but for now we should focus on converting the existing commands.

yeah. we should not work on it right now. and i was not proposing to work on this immediately. just want to ask for more inputs, so that we don't forget it. if this makes sense, i would like to add a ticket to track this work.

**Comment by denesb** [comment]
> yeah. we should not work on it right now. and i was not proposing to work on this immediately. just wanted to ask for more inputs, so that we don't forget it. if this makes sense, i would like to add a ticket to track this work.

I think we should ask @mykaul and @tzach for input. Maybe open a ticket about it and CC them to have a focused discussion about it (it could be lost in the noise in this ticket).

**Comment by denesb** [comment]
Status report. Out of the 48 commands total:
* 38 is implemented
* 3 has open PRs
* 1 has a draft PR
* 2 is WIP
* 4 not started on yet

**Comment by tchaikov** [comment]
@denesb could you link the corresponding item in the task list to #17375?

**Comment by tchaikov** [comment]
i am now working on `tablestats`.

**Comment by tchaikov** [comment]
@denesb could you link the corresponding item in the task list to #17387?

**Comment by denesb** [comment]
Done. Yes, anything with `stats` or `histogram` in its name is a pain to implement.

**Comment by tchaikov** [comment]
i am now working on `info`.

**Comment by tchaikov** [comment]
@denesb could you link the corresponding item in the task list to #17498?

**Comment by denesb** [comment]
We now have open PRs for all remaining commands, we just need to start draining the PR queue.

The light at the end of the tunnel is visible.

**Comment by mykaul** [comment]
> The light at the end of the tunnel is visible.

As long as it's not an incoming train!

Well done - let's see what we need to do to get rid of the Java stuff then!

**Comment by denesb** [comment]
All commands are in. The native nodetool is now feature complete. The last remaining PR preventing us to switch to using it is https://github.com/scylladb/scylladb/pull/17168.

**Comment by mykaul** [comment]
> All commands are in. The native nodetool is now feature complete. The last remaining PR preventing us to switch to using it is #17168.

Bravo!

**Comment by denesb** [comment]
All required content is in. Bugfixes will get their own issues. Closing.
