### ISSUE TITLE
Add tasks covering node-operations

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#15852]
This is an umbrella issue, covering the task-manager task hierarchy for node-operations.
The idea is to have one top-level task covering the entire operation (or saga), with child-tasks covering the concrete sub-tasks done as part of it (think streaming).
In the case of raft-based node-operations, the top level task might be a virtual one, derived from data structures maintained by group 0 (topology table).

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylladb/pull/15460
- [ ] https://github.com/scylladb/scylladb/pull/15572 
- [ ] https://github.com/scylladb/scylladb/pull/15546
```

**Comment by denesb** [comment]
@Deexie please make sure all PRs related to this, reference this issue.

**Comment by mykaul** [comment]
Is this still on track for 6.0?

**Comment by denesb** [comment]
> Is this still on track for 6.0?

No, there has been no progress on this for months, it was halted to work on tablets instead.

**Comment by Deexie** [comment]
Solved with https://github.com/scylladb/scylladb/pull/16374, closing
