### ISSUE TITLE
Implemening Code coverage

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#16323]
This is an issue that is set up to track code coverage support in our code-base.
The implementation of code coverage is as follows:

```[tasklist]
### Tasks
- [x] 1. Install packages to be eventually used by the code coverage processing code and update dbuild
- [x] 2. Backport dumping the profile on SIGTERM for Scylla  (See note below)
- [x] 3. Add code coverage **handling** support to unit_tests (collecting coverage data into correct directories)
- [x] 4. Add processing libraries for adding coverage processing capabilities
- [x] 5. Add coverage processing support to unit_test
```

Notes:
* The commit for step 3 is scylladb/scylla-enterprise@a7096ebb28d06161599e8acc0641b3870713d023
* Steps should be sequential
* To achieve full functionality we will have to also add CI support for this

**Comment by eliransin** [comment]
1 Was done (#16357)

**Comment by eliransin** [comment]
#16784 is going to attend all remaining TODOs

**Comment by eliransin** [comment]
Code coverage now supported in Scylla source code and in jenkins BYO so this can be closed.
