### ISSUE TITLE
auth: move system_auth under RAFT (epic)

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/scylladb#16970]
An umbrella issue for all the issues on the subject of moving system_auth under RAFT:

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylladb/issues/12697
- [ ] https://github.com/scylladb/scylladb/issues/15221
- [ ] https://github.com/scylladb/scylladb/issues/15251
- [ ] https://github.com/scylladb/scylladb/issues/11157
- [ ] https://github.com/scylladb/scylladb/issues/17061
- [ ] https://github.com/scylladb/scylladb/issues/17264
- [ ] https://github.com/scylladb/scylladb/issues/3166
- [ ] https://github.com/scylladb/scylladb/issues/17713
- [ ] https://github.com/scylladb/scylladb/issues/17736
- [ ] https://github.com/scylladb/scylladb/issues/17737
```

**Comment by asias** [comment]
@psarna do we have any design docs for the sytem_auth under raft thing?

**Comment by mykaul** [comment]
> @psarna do we have any design docs for the sytem_auth under raft thing?

@ptrsmrn I reckon.

**Comment by nuivall** [comment]
@asias yes, added link to google drive. (https://docs.google.com/document/d/1yXFsCnwPKy2eRTkiaiFATSa1k6oJWCIdO7pQFVD3aa8/edit?usp=sharing)
It's a draft (btw dunno what's the process to convert draft to non draft).

**Comment by asias** [comment]
> @asias yes, added link to google drive. (https://docs.google.com/document/d/1yXFsCnwPKy2eRTkiaiFATSa1k6oJWCIdO7pQFVD3aa8/edit?usp=sharing) It's a draft (btw dunno what's the process to convert draft to non draft).

I looked at the doc. It does not contain how the data replication would happen though. For example, I am interested in how and when the data would be replicated to everywhere if the replication strategy is LocalStrategy. And what happens if some nodes are down. When will they get the data after restart?

**Comment by kbr-scylla** [comment]
The data is replicated by Raft. The leader of group 0 is replicating committed commands to followers that don't have them (or snapshot if they are too far behind) and they apply those commands. The commands update the local table.

**Comment by asias** [comment]
> The data is replicated by Raft. The leader of group 0 is replicating committed commands to followers that don't have them (or snapshot if they are too far behind) and they apply those commands. The commands update the local table.

Ok. This is what I thought and thanks for confirming. I was confused by that the bare insert into system_auth_v2.roles was not replicated.

**Comment by kostja** [comment]
> @asias yes, added link to google drive. (https://docs.google.com/document/d/1yXFsCnwPKy2eRTkiaiFATSa1k6oJWCIdO7pQFVD3aa8/edit?usp=sharing) It's a draft (btw dunno what's the process to convert draft to non draft).

The process is to submit description of the actual implementation to docs/dev as a markdown document

**Comment by ptrsmrn** [comment]
We won't complete everything in 6.0.
@dani-tweig what to do, change the milestone to 6.1 (and potentially next releases), split the epic?
cc @mykaul

**Comment by dani-tweig** [comment]
@mykaul , should it be 6.1, or should I open 6.0.1?

**Comment by mykaul** [comment]
Can we move this one or close this one and move remaining item to https://github.com/scylladb/scylladb/issues/18867 ? 6.0 is going to GA.

**Comment by ptrsmrn** [comment]
> Can we move this one or close this one and move remaining item to #18867 ? 6.0 is going to GA.

@mykaul I moved 2 remaining items #17738 & #18750 to #18867 per request, which completes work for this epic.
