### ISSUE TITLE
Missing gossiper updates

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#17493]
This is an issue to describe the possible root cause of multiple different issues found by tests, and document findings from investigation.

In https://github.com/scylladb/scylladb/issues/16902, a joining node finished the bootstrap correctly and entered the NORMAL status. However one of the nodes in the cluster did not observe the NORMAL status, which was detected by SCT health check. By investigating gossipinfo output, I determined that the node does not have the updated STATUS application state.

https://github.com/scylladb/scylladb/issues/15602 looks the same, except it happened on dtest. The test waits until a replacing node enters NORMAL state by checking how other nodes see its state in gossiper. The test timed out because one of the nodes never saw the replacing node entering NORMAL state.

In https://github.com/scylladb/scylla-enterprise/issues/3720 there was a schema change and after each schema change all nodes start gossiping the current schema version. SCT detected that one of the nodes observes an outdated (pre-change) version for another node (in gossipinfo and system.peers), this state remained until the next schema change.

In https://github.com/scylladb/scylladb/issues/16668 a node replaced another, and then decommissioned. During decommission there was a crash on another node. Turns out that another node never saw the replacing node enter NORMAL state -- it kept seeing it as if it was still doing the replace. (There was never `handle_state_normal` call that would appropriately update `token_metadata`).

In https://github.com/scylladb/scylladb/issues/15393 a node got stuck during bootstrap waiting for schema versions to synchronize across the cluster.  And apparently it keeps seeing an outdated schema version for one of the nodes in gossip, even though logs of that node show that it transitioned to new version.

---

All these issues lead to a single hypothesis -- there is some bug in gossiping algorithm that causes application state updates to go missing. It's not transient, once node A obtains new application states for node B but somehow one of the application state updates goes missing, then A will never get update for this particular app state of node B, regardless of how long they keep gossiping. The way to go out of this is for node B to increase the version of this app state (e.g. for schema, do another schema change). Or reboot which will increase the generation number of its endpoint state)

EDIT update: actual root cause described in fix https://github.com/scylladb/scylladb/pull/18184
the below description is for old hypothesis

As for possible explanations what the bug could be, we have one. After digging into the code I saw this
```cpp
namespace gms {
namespace version_generator {
// In the original Cassandra code, version was an AtomicInteger.
// For us, we run the gossiper on a single CPU, and don't need to use atomics.
static version_type version;

version_type get_next_version() noexcept
{
    return ++version;
}
```
knowing from experience that assertions through comments never work (unlike `assert` macro or similar mechanism), I found this immediately suspicious.

@piodul investigated this further and indeed, after putting an actual `assert` there (that it's called only from shard 0), Scylla immediately crashes. So we know we have a data race in gossiper. The non-shard0 access comes from updating CACHE_HITRATES in service/misc_services.cc

From reading the code, we came up with possible theoretical scenario in which this data race could cause missing application state updates. Gossiper exchanges application states as follows: each node remembers the latest application states it saw for every other node, and calculates the max version of those states. When doing the exchange, it receives only application states with versions greater than this max version.

So the scenario is:

- shard 1 on node A calls `get_next_version()` which observes version `v - 1` and hangs before storing `v` (gets preempted or sth)
- node A calls `add_local_application_state` (always happens on shard 0), calls `get_next_version()` which observes version `v - 1`, increments it and returns `v` which is used for the updated app state.
- node A calls `add_local_application_state` again, calls `get_next_version()` which observes version `v`, increments it and returns `v + 1` which his used for this updated app state.
- gossip message handler called on node A, which causes node A to return its app states to node B. The max version is `v + 1`
- shard 1 on A resumes and stores version `v`
- node A calls `add_local_application_state` again, calls `get_next_version()` which observes version `v`, increments it and returns `v + 1` which his used for this updated app state.
- node B will never get that last app state because it already assumes that max version on node A is `v + 1`, and we only obtain states with versions greater than last max.

@piodul ran a test which some modifications to Scylla:
- make the cache hitrates updater to run more frequently
- putting an assertion in `add_local_application_state` that it only observes strictly increasing version numbers
- running a test that performs schema changes in a loop

and after a few hours, the assertion was triggered.

But we never managed to reproduce a scenario where the two `add_local_application_state` calls which reuse the same version are interleaved with a gossip exchange that would actually cause the bug. Plus the cache hitrates updater which usually runs every 1 second or so, was modified to run thousands of times per second to trigger the data race more often.

In fact this scenario (where a gossip exchange timing correlates with the data race timing) seems very unlikely already with the frequent cache hitrate updating, and even extremely unlikely with regular cache hitrate updating.

But we don't have any other explanation for the observed failures.

So the plan for now is to fix the data race and see if we keep observing similar failures in our tests for the next month or 2. If nothing like that appears again, we will assume that it was the data race. Otherwise we'll need to investigate further.
```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylladb/issues/15393
- [ ] https://github.com/scylladb/scylladb/issues/15602
- [ ] https://github.com/scylladb/scylladb/issues/16668
- [ ] https://github.com/scylladb/scylladb/issues/16902
- [ ] https://github.com/scylladb/scylla-enterprise/issues/3720
- [ ] https://github.com/scylladb/scylladb/issues/18118
```

**Comment by kbr-scylla** [comment]
Note that one of the failures listed above was reproduced **in 5.4**

**Comment by kbr-scylla** [comment]
Another possible occurrence: https://github.com/scylladb/scylladb/issues/17349

**Comment by kbr-scylla** [comment]
The issue is still happening: https://github.com/scylladb/scylladb/issues/18118

**Comment by kbr-scylla** [comment]
Test:
```python3
import asyncio
import pytest

from test.pylib.manager_client import ManagerClient
from test.topology.conftest import skip_mode

@pytest.mark.asyncio
@skip_mode('release', 'error injections are not supported in release mode')
async def test_gossip_boot(manager: ManagerClient):
    cfg = {'error_injections_at_startup': ['force_gossip_based_join']}
    servers = [await manager.server_add(config=cfg, timeout=30) for _ in range(3)]
    logs = [await manager.server_open_log(s.server_id) for s in servers]

    for log in logs:
        for s in servers:
            await log.wait_for(f'handle_state_normal for {s.ip_addr}.*finished', timeout=30)
```

This sleep gives ~100% reproducibility:
```diff
diff --git a/gms/gossiper.cc b/gms/gossiper.cc
index a17a416401..736857da98 100644
--- a/gms/gossiper.cc
+++ b/gms/gossiper.cc
@@ -1298,6 +1298,9 @@ future<> gossiper::replicate(inet_address ep, endpoint_state es, permit_id pid)
             });
         }
      });
+
+    co_await sleep_abortable(std::chrono::milliseconds{1000});
+
     // Second pass: set replicated endpoint_state on all shards
     // Must not throw
     try {
```
