### ISSUE TITLE
[object-storage, tablets]: Integrated restore for tablets-enabled keyspaces

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18392]
This epic covers the fully-integrated process of restoring tablets-enabled keyspace, consisting of:

- [ ] Automatic ingestion of sstables from S3 snapshot
- [ ] Cluster-wide api for distributed restore
- [ ] Integration of cluster-wide backup with scylla-manager

The gist of it is that when restoring data from a snapshot of tablets-enabled table we can infer the desired tablet size (and number of tablets) from the sstable with the largest token range, such that every sstable will be confined to at most one tablet.
Then we can allocate the required number of tablets in the table (as empty tablets), and then each tablet replica can load all sstables that fall in its token range and compact them together (possibly inline with restore so to reduce space amplification on disk).
The whole process should be scheduled by the tablet scheduler.

**Comment by mykaul** [comment]
@regevran - status?

**Comment by regevran** [comment]
> status?

I could ask this issue [to be closed](https://github.com/scylladb/scylladb/issues/18391#issuecomment-2585675251) too, but I prefer keeping this issue for future reference.
We'll not have a cluster-wide restore - yet - I prefer having this issue open, as I linked to it from the document that describes the work: [For Tablet, build tablets map based...](https://docs.google.com/document/d/1rEHPDbjY10e5oMVi5OcHqQ3HQRDoLG4OXZnC_8l1Eg8/edit?tab=t.wy6n8l1g6xin).

**Comment by regevran** [comment]
Closed as there are many other issues covering restore. e.g. #21100.
