### ISSUE TITLE
[object-storage, tablets]: Integrated backup for tablets-enabled keyspaces

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18391]
This epic covers the fully-integrated process of backing up tablets-enabled keyspace, consisting of:

- [ ] Cluster-wide api for distributed snapshot
- [ ] Automatic copy of sstables in a snapshot to S3
- [ ] Cluster-wide api for backup
- [ ] Integration of cluster-wide backup with scylla-manager

**Comment by regevran** [comment]
We chose a slightly different approach.
We have a native API, but we don't have _cluster wide_ API.
We also don't have plans for such an API in 2025, Scylla Manager is still planned to control cluster-wide backup.
I suggest closing this issue as "not planned".
