### ISSUE TITLE
[Epic] Tablet documentation changes

### ISSUE THREAD

**Issue by dani-tweig** [scylladb/scylladb#18597]
This epic will consist all the documentation changes required due to the Tablet feature.

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylladb/issues/18595
- [ ] https://github.com/scylladb/scylladb/issues/18670
- [ ] https://github.com/scylladb/scylladb/issues/18895
```

**Comment by dani-tweig** [comment]
![image](https://github.com/scylladb/scylladb/assets/155957822/d7d05562-580f-49b2-b896-4a2c389a7654)

dont you see this option?

**Comment by dani-tweig** [comment]
Lesson for next time; let you open documentation-related issues :)

Let me know which additional tasks you want to add and I will do that

**Comment by mykaul** [comment]
Why is this on 6.0? Is this still being worked on?
