### ISSUE TITLE
[epic] Tablets - gaps from vnodes

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#19087]
- [ ] https://github.com/scylladb/scylladb/issues/18180
- [ ] https://github.com/scylladb/scylladb/issues/18068
- [ ] https://github.com/scylladb/scylladb/issues/16317
- [ ] https://github.com/scylladb/scylladb/issues/16411
- [ ] https://github.com/scylladb/scylladb/issues/17575
- [ ] https://github.com/scylladb/scylladb/issues/16789

**Comment by denesb** [comment]
https://github.com/scylladb/scylladb/issues/17575 was replaced with SCYLLADB-103.
