### ISSUE TITLE
`raft_operation_timeout_error`s appearing in various topology operations during SCT testing

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#19105]
This is an umbrella issue to gather different reports from QA where we encounter `raft_operation_timeout_error` during SCT testing.

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylladb/issues/18959
- [ ] https://github.com/scylladb/scylladb/issues/19031
- [ ] https://github.com/scylladb/scylladb/issues/18821
- [ ] https://github.com/scylladb/scylladb/issues/19231
```

@gleb-cloudius is already investigating https://github.com/scylladb/scylladb/issues/19031.

But all of them likely have the same root cause. So we should rerun tests for all of them once https://github.com/scylladb/scylladb/issues/19031 is fixed.

**Comment by kbr-scylla** [comment]
Another report: https://github.com/scylladb/scylladb/issues/19231

**Comment by kbr-scylla** [comment]
So it looks like compaction code and memtable flush code -- long-running background tasks -- are holding a lock that prevents topology metadata from being updated, which causes `storage_service::topology_state_load` to wait, which causes group 0 apply to wait, which causes any further group 0 requests (schema changes, topology operations, etc.) executed concurrently with these background tasks to wait on them and eventually timeout.

This looks like a bug -- we shouldn't lock metadata updates for during such long running operations.

More details here from @gleb-cloudius: https://github.com/scylladb/scylladb/issues/18821#issuecomment-2186185254

cc @bhalevy @denesb @tgrabiec @raphaelsc 

I'm reassigning to storage group.

**Comment by raphaelsc** [comment]
I'll cook something to fix this, thanks.

**Comment by bhalevy** [comment]
> I'll cook something to fix this, thanks.

@raphaelsc / @Deexie
I think we can go with something along these lines:
```diff
diff --git a/replica/table.cc b/replica/table.cc
index 1493d54c06..c6f354812c 100644
--- a/replica/table.cc
+++ b/replica/table.cc
@@ -979,10 +980,19 @@ compaction_group_list& table::compaction_groups() const noexcept {
 }
 
 future<> table::parallel_foreach_compaction_group(std::function<future<>(compaction_group&)> action) {
-    rwlock::holder shared_lock = co_await _sg_manager->get_rwlock().hold_read_lock();
-    co_await coroutine::parallel_for_each(compaction_groups(), [&] (compaction_group& cg) {
-        return action(cg);
-    });
+    auto n = compaction_groups().size();
+    if (n == 1) {
+        return action(compaction_groups().front());
+    }
+    std::vector<future<>> futures;
+    futures.reserve(n);
+    for (auto& cg : compaction_groups()) {
+        auto f = action(cg);
+        if (!f.available()) {
+            futures.emplace_back(std::move(f));
+        }
+    }
+    return when_all_succeed(std::move(futures));
 }
 
 future<> table::safe_foreach_sstable(const sstables::sstable_set& set, noncopyable_function<future<>(const sstables::shared_sstable&)> action) {
```

and similarly for `for_each_storage_group_gently`.

The lock is supposed to only protect the list of storage/compaction groups, not their content.

**Comment by raphaelsc** [comment]
> > I'll cook something to fix this, thanks.
> 
> @raphaelsc / @Deexie I think we can go with something along these lines:
> 
> ```diff
> diff --git a/replica/table.cc b/replica/table.cc
> index 1493d54c06..c6f354812c 100644
> --- a/replica/table.cc
> +++ b/replica/table.cc
> @@ -979,10 +980,19 @@ compaction_group_list& table::compaction_groups() const noexcept {
>  }
>  
>  future<> table::parallel_foreach_compaction_group(std::function<future<>(compaction_group&)> action) {
> -    rwlock::holder shared_lock = co_await _sg_manager->get_rwlock().hold_read_lock();
> -    co_await coroutine::parallel_for_each(compaction_groups(), [&] (compaction_group& cg) {
> -        return action(cg);
> -    });
> +    auto n = compaction_groups().size();
> +    if (n == 1) {
> +        return action(compaction_groups().front());
> +    }
> +    std::vector<future<>> futures;
> +    futures.reserve(n);
> +    for (auto& cg : compaction_groups()) {
> +        auto f = action(cg);
> +        if (!f.available()) {
> +            futures.emplace_back(std::move(f));
> +        }
> +    }
> +    return when_all_succeed(std::move(futures));
>  }
>  
>  future<> table::safe_foreach_sstable(const sstables::sstable_set& set, noncopyable_function<future<>(const sstables::shared_sstable&)> action) {
> ```
> 
> and similarly for `for_each_storage_group_gently`.
> 
> The lock is supposed to only protect the list of storage/compaction groups, not their content.

we need to protect against concurrent cleanup. Botond suggested copy-update-swap the list on updates.

**Comment by Deexie** [comment]
> > I'll cook something to fix this, thanks.
> 
> @raphaelsc / @Deexie I think we can go with something along these lines:
> 
> ```diff
> diff --git a/replica/table.cc b/replica/table.cc
> index 1493d54c06..c6f354812c 100644
> --- a/replica/table.cc
> +++ b/replica/table.cc
> @@ -979,10 +980,19 @@ compaction_group_list& table::compaction_groups() const noexcept {
>  }
>  
>  future<> table::parallel_foreach_compaction_group(std::function<future<>(compaction_group&)> action) {
> -    rwlock::holder shared_lock = co_await _sg_manager->get_rwlock().hold_read_lock();
> -    co_await coroutine::parallel_for_each(compaction_groups(), [&] (compaction_group& cg) {
> -        return action(cg);
> -    });
> +    auto n = compaction_groups().size();
> +    if (n == 1) {
> +        return action(compaction_groups().front());
> +    }
> +    std::vector<future<>> futures;
> +    futures.reserve(n);
> +    for (auto& cg : compaction_groups()) {
> +        auto f = action(cg);
> +        if (!f.available()) {
> +            futures.emplace_back(std::move(f));
> +        }
> +    }
> +    return when_all_succeed(std::move(futures));
>  }
>  
>  future<> table::safe_foreach_sstable(const sstables::sstable_set& set, noncopyable_function<future<>(const sstables::shared_sstable&)> action) {
> ```
> 
> and similarly for `for_each_storage_group_gently`.
> 
> The lock is supposed to only protect the list of storage/compaction groups, not their content.

In this solution (and I think in copy-update-swap too but I'm not sure if I understand the idea properly) we need to somehow deal with compaction group's use-after-free, no? But I think if we additionally enter compaction group's gate then it would be enough (`update_effective_replication_map` would hang only on split). Maybe a compaction group should also abort its operations on `compaction_group::stop`.

**Comment by raphaelsc** [comment]
I am cooking a patch already.

**Comment by gleb-cloudius** [comment]
> 
> In this solution (and I think in copy-update-swap too but I'm not sure if I understand the idea properly) we need to somehow deal with compaction group's use-after-free, no? But I think if we additionally enter compaction group's gate then it would be enough (`update_effective_replication_map` would hang only on split). Maybe a compaction group should also abort its operations on `compaction_group::stop`.

Hang for how long? `update_effective_replication_map` should not hang for duration of any heavy IO operation (compaction, flush, cleanup). It may wait for a shot CPU task of course.

**Comment by raphaelsc** [comment]
> > In this solution (and I think in copy-update-swap too but I'm not sure if I understand the idea properly) we need to somehow deal with compaction group's use-after-free, no? But I think if we additionally enter compaction group's gate then it would be enough (`update_effective_replication_map` would hang only on split). Maybe a compaction group should also abort its operations on `compaction_group::stop`.
> 
> Hang for how long? `update_effective_replication_map` should not hang for duration of any heavy IO operation (compaction, flush, cleanup). It may wait for a shot CPU task of course.

turns out that function can proceed without any locking whatsoever.

**Comment by raphaelsc** [comment]
I think Aleksandra said it would only hang on split because it's the only one that waits on a future, but that should always be an available future in practice (stopping storage object that is empty and previously split into two, so no I/O)

**Comment by kbr-scylla** [comment]
Note @mykaul I think this should be a blocker for 2024.2.

**Comment by kbr-scylla** [comment]
More timeout reports:
https://github.com/scylladb/scylladb/issues/18959
https://github.com/scylladb/scylladb/issues/19573
https://github.com/scylladb/scylladb/issues/19585

**Comment by bhalevy** [comment]
@raphaelsc is not doing any active work on this after https://github.com/scylladb/scylladb/pull/19469
Let's see if the problem is reproduced after dropping the rwlock

**Comment by kbr-scylla** [comment]
Note that https://github.com/scylladb/scylladb/pull/19719 should be backported to 6.0.
If it's too complex, then we should wait for 6.1 and base 2024.2 on that.

**Comment by raphaelsc** [comment]
PR with resolved conflicts: https://github.com/scylladb/scylladb/pull/19808

**Comment by kbr-scylla** [comment]
Removed https://github.com/scylladb/scylladb/issues/19025 from the list, the suspected root cause is different

**Comment by kbr-scylla** [comment]
Blocked from closing by https://github.com/scylladb/scylladb/issues/19031 which is blocked because we can't get a passing longevity because we're waiting for https://github.com/scylladb/scylla-cluster-tests/pull/7625 to get merged

**Comment by kbr-scylla** [comment]
All dependent issues were closed, and we can close this one as well.

(Backport of the fix to 6.0 is still pending though.)
