### ISSUE TITLE
[Epic] Migrate vnodes to tablets

### ISSUE THREAD

**Issue by dani-tweig** [scylladb/scylladb#19121]
@avikivity , @tzach , @bhalevy , @mykaul , @tgrabiec 

An epic describing the move from vnodes to tablet.

Current known tasks:

- [ ] Write a requirements document
- [ ] Research different solutions
- [ ] Write a design document
- [ ] Implementation

**Comment by bhalevy** [comment]
Postponing milestone as we didn't get to it for 2025.4
