### ISSUE TITLE
cql: fix LIMIT clause (epic) - part 1

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/scylladb#19275]
LIMIT clause doesn't work for all CQL queries. This epic lists all the issues relevant to correctness of applying the LIMIT clause (not its performance nor other aspects).

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/core-frontend/issues/7
- [ ] https://github.com/scylladb/scylladb/issues/5361
- [ ] https://github.com/scylladb/scylladb/issues/5362
- [ ] https://github.com/scylladb/scylladb/issues/17237
- [ ] https://github.com/scylladb/scylladb/issues/5363
```

**Comment by mykaul** [comment]
@ptrsmrn - unsure why it's a P3, and I'm hoping we are making progress here.

**Comment by ptrsmrn** [comment]
@mykaul changed from P3 to P2. Yes, we're making progress, @KrzaQ is about to close 1 bug, which will in turn close 3 issues.
