### ISSUE TITLE
Drop the replace_address options

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#19480]
Since https://github.com/scylladb/scylladb/commit/1577aa8098cac7bc2ef0b7f9523044383e14896e (5.2), the `replace_address` and `replace_address_first_boot` options are deprecated and their usage is discouraged, and warned about (when used).
Instead, the user should use the `replace_node_first_boot` which states the replaced node's host_id rather than its ip address.

This epic consists of:

```[tasklist]
### Tasks
- [ ] scylla-dtest: [Stop testing the replace_address options](https://github.com/scylladb/scylla-dtest/issues/4503)
- [ ] scylla-cluster-tests: [Stop testing the replace_address options](https://github.com/scylladb/scylla-cluster-tests/issues/7741)
- [ ] scylla-manager: [Use the replace_node_first_boot option rather than replace_address](https://github.com/scylladb/scylla-manager/issues/3901)
- [ ] siren: [Use the replace_node_first_boot option rather than replace_address](https://github.com/scylladb/siren/issues/11494)
- [ ] Drop the replace_address options from documentation
- [ ] Drop support for the replace_address option in scylla
```

**Comment by bhalevy** [comment]
Cc @dani-tweig 
I hope I captured all dependencies above, before dropping support of those legacy options in scylla itself.

**Comment by bhalevy** [comment]
@vladzcloudius are there any changes needed for the field-cloud admin infrastructure?

**Comment by mykaul** [comment]
@bhalevy : 
-  https://github.com/scylladb/scylla-operator/blob/2c62fa0e3886c3e4995096dadb009e4c36c340b0/pkg/scyllaclient/config_client.go#L66 ? (perhaps not interesting - see https://github.com/scylladb/scylla-operator/blob/2c62fa0e3886c3e4995096dadb009e4c36c340b0/pkg/api/scylla/v1/types_cluster.go#L807 )
- https://github.com/scylladb/scylla-ansible-roles/blob/ebe67fa4df358028c9e7da8ac668bd6d5b04787f/example-playbooks/replace_node/replace_node.yml#L185 
- Siren code (private repo...) - please search.

**Comment by vladzcloudius** [comment]
> @vladzcloudius are there any changes needed for the field-cloud admin infrastructure?

Nope.

**Comment by kbr-scylla** [comment]
Ref https://github.com/scylladb/scylladb/issues/12277
