### ISSUE TITLE
scylla-sstable: add native S3 support

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#20532]
```[tasklist]
### Tasks
- [ ] Allow providing sstables located in S3 as arguments to all scylla-sstable commands.
- [ ] Allow providing S3 as the output for scylla-sstable commands which produce sstables.
- [ ] Add a `download` command, which downloads an sstable located in S3, to local storate.
- [ ] Add an `upload` command, which uploads an sstable from local storage, to S3.
```

**Comment by tchaikov** [comment]
@denesb hi Botond, probably we can materialize some of the subtasks as separate issues, so we can divide and conquer them. i can take care of some of them when i have some free cycles.

**Comment by denesb** [comment]
> @denesb hi Botond, probably we can materialize some of the subtasks as separate issues, so we can divide and conquer them. i can take care of some of them when i have some free cycles.

Good idea. I converted the issue to an epic and created a sub-issue for each task, also assigning priorities. I am not that familiar with how our S3 support works, so I might need some help on hashing out the details.
I have some questions:
* How does specifying the location of an sstable in S3 works? Is it based on a regular URL? Or does one need multiple pieces of information to locate one sstable?
* Is it possible to specify multiple sstables in a generic manner possible? Similar to how one can provide a path to a directory on local storage, to cover all sstables located in said directory.
* Is it possible to provide some S3 URL as the place to write a new sstable to?
* What is the minimum configuration required for scylla-sstable to have working access to S3? Do we need some server-address? Credentials?
* Do we need access to ScyllaDB internal system tables to enumerate sstables on S3?

**Comment by tchaikov** [comment]
> > @denesb hi Botond, probably we can materialize some of the subtasks as separate issues, so we can divide and conquer them. i can take care of some of them when i have some free cycles.
> 
> Good idea. I converted the issue to an epic and created a sub-issue for each task, also assigning priorities. I am not that familiar with how our S3 support works, so I might need some help on hashing out the details. I have some questions:
> 
>     * How does specifying the location of an sstable in S3 works? Is it based on a regular URL? Or does one need multiple pieces of information to locate one sstable?

we use the name of "endpoint" configfured in `object_storage.yaml`. the name is practically an address or domain name of an AWS [endpoint](https://docs.aws.amazon.com/general/latest/gr/s3.html. but if we want to expand the the support to other object storage provider, it could be just an identifier. see https://github.com/scylladb/scylladb/blob/master/docs/dev/object_storage.md#introduction. 
> 
>     * Is it possible to specify multiple sstables in a generic manner possible? Similar to how one can provide a path to a directory on local storage, to cover all sstables located in said directory.

we could use "prefix" and probably a "filter" so that we can list all objects whose key names match this prefix , and the filter them with a glob or regex or a postfix. so that we can only only download the TOC components, or stats components.
> 
>     * Is it possible to provide some S3 URL as the place to write a new sstable to?

i think with the helpers under `utils/s3`, it is possible. but because we would need the a set of parameters like the bucket, credentials to initialize the s3 client, probably it's more handy to use the "endpoint" to specify the "place".

> 
>     * What is the minimum configuration required for scylla-sstable to have working access to S3? Do we need some server-address? Credentials?

again, see https://github.com/scylladb/scylladb/blob/master/docs/dev/object_storage.md#introduction .

> 
>     * Do we need access to ScyllaDB internal system tables to enumerate sstables on S3?

for the s3 storage backend, we do have a system table named "system.sstables" for tracking the sstable stored on S3. the `sstables_registry_components_lister` is using it. but i think, as an alternative, we can also encode the keyspace, table, node_id in the prefix for the forthcoming tiered storage, but it's not discussed yet.

**Comment by denesb** [comment]
@tchaikov I'm going to assign all the issues to myself for planning purposes, but feel free to take any of them and assign to yourself as well, if you want to pick it up.

**Comment by tchaikov** [comment]
@denesb could you please update this issue per your remarks at https://github.com/scylladb/scylladb/pull/20863#issuecomment-2587108422 ? also, IIUC, we might want to close it or replace it with an issue on redistributing awscli and corresponding documentation.

**Comment by denesb** [comment]
> [@denesb](https://github.com/denesb) could you please update this issue per your remarks at [#20863 (comment)](https://github.com/scylladb/scylladb/pull/20863#issuecomment-2587108422) ? also, IIUC, we might want to close it or replace it with an issue on redistributing awscli and corresponding documentation.

Done. I closed the relevant issues and opened a new one to document the s3 dir structure and how to upload/download sstables with `awscli`.

**Comment by bhalevy** [comment]
@kreuzerkrieg I see that https://github.com/scylladb/scylladb/commit/83ea1877ab6a0bc08560e8b7e467f5bf5661c852 only Ref'ed this issue but didn't fix it.
What's left to be done here?

**Comment by denesb** [comment]
> [@kreuzerkrieg](https://github.com/kreuzerkrieg) I see that [83ea187](https://github.com/scylladb/scylladb/commit/83ea1877ab6a0bc08560e8b7e467f5bf5661c852) only Ref'ed this issue but didn't fix it. What's left to be done here?

https://github.com/scylladb/scylladb/issues/22438

We need to document everything about sstable on S3 and where can one find additional metadata. This should be an engineering oriented documents, so that when someone is assigned to investigate some problem related to S3, they can catch up on what they will find in S3 and how to access them.

**Comment by kreuzerkrieg** [comment]
> [@kreuzerkrieg](https://github.com/kreuzerkrieg) I see that [83ea187](https://github.com/scylladb/scylladb/commit/83ea1877ab6a0bc08560e8b7e467f5bf5661c852) only Ref'ed this issue but didn't fix it. What's left to be done here?

it doesnt cover these:
1. scp-notation: $endpoint:$bucket/$prefix/$object_name
2. --object-storage-endpoint=$endpoint argument

**Comment by denesb** [comment]
> > [@kreuzerkrieg](https://github.com/kreuzerkrieg) I see that [83ea187](https://github.com/scylladb/scylladb/commit/83ea1877ab6a0bc08560e8b7e467f5bf5661c852) only Ref'ed this issue but didn't fix it. What's left to be done here?
> 
> it doesnt cover these:
> 
>     1. scp-notation: $endpoint:$bucket/$prefix/$object_name
> 
>     2. --object-storage-endpoint=$endpoint argument

We don't need to support these from functionality POV? When I wrote that cover letter, I didn't yet know what the best way to address sstables located in S3 would be. So I listed multiple methods.

**Comment by kreuzerkrieg** [comment]
> > > > [@kreuzerkrieg](https://github.com/kreuzerkrieg) I see that [83ea187](https://github.com/scylladb/scylladb/commit/83ea1877ab6a0bc08560e8b7e467f5bf5661c852) only Ref'ed this issue but didn't fix it. What's left to be done here?
> > > 
> > > 
> > > it doesnt cover these:
> > > ```
> > > 1. scp-notation: $endpoint:$bucket/$prefix/$object_name
> > > 
> > > 2. --object-storage-endpoint=$endpoint argument
> > > ```
> > 
> > 
> > We don't need to support these from functionality POV? When I wrote that cover letter, I didn't yet know what the best way to address sstables located in S3 would be. So I listed multiple methods.
> 
> but in any case we cant close this one as long as we dont address these, right? [#20537](https://github.com/scylladb/scylladb/issues/20537) [#20538](https://github.com/scylladb/scylladb/issues/20538) [#20536](https://github.com/scylladb/scylladb/issues/20536)

ah, I see, they are closed as not planned. then the documentation thingy is the only one to take care of

**Comment by denesb** [comment]
> > > > > [@kreuzerkrieg](https://github.com/kreuzerkrieg) I see that [83ea187](https://github.com/scylladb/scylladb/commit/83ea1877ab6a0bc08560e8b7e467f5bf5661c852) only Ref'ed this issue but didn't fix it. What's left to be done here?
> > > > 
> > > > 
> > > > it doesnt cover these:
> > > > ```
> > > > 1. scp-notation: $endpoint:$bucket/$prefix/$object_name
> > > > 
> > > > 2. --object-storage-endpoint=$endpoint argument
> > > > ```
> > > 
> > > 
> > > We don't need to support these from functionality POV? When I wrote that cover letter, I didn't yet know what the best way to address sstables located in S3 would be. So I listed multiple methods.
> > 
> > 
> > but in any case we cant close this one as long as we dont address these, right? [#20537](https://github.com/scylladb/scylladb/issues/20537) [#20538](https://github.com/scylladb/scylladb/issues/20538) [#20536](https://github.com/scylladb/scylladb/issues/20536)
> 
> ah, I see, they are closed as not planned. then the documentation thingy is the only one to take care of

Yes. The document should be in `docs/dev`.

**Comment by mykaul** [comment]
What's missing to complete this?

**Comment by denesb** [comment]
Nothing, we can close.
