### ISSUE TITLE
tablets: alter keyspace follow-ups (epic) - improvement ideas

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/scylladb#20666]
Follow-ups to https://github.com/scylladb/scylladb/pull/16723
Part 1 - https://github.com/scylladb/scylladb/issues/19123
Part 2 - https://github.com/scylladb/scylladb/issues/20665

```[tasklist]
### Tasks
- [ ] wait for alter tablets ks not to timeout on server/drivers side or just increase cqlsh timeout, do we have an issue for that? (per https://github.com/scylladb/scylladb/issues/16129#issuecomment-2026939776)
- [ ] extend tests coverage, add e2e?
- [ ] handle the possibility of submitting too many mutations at once, per https://github.com/scylladb/scylladb/pull/16723#discussion_r1587176730
- [ ] integrate with virtual task API https://github.com/scylladb/scylladb/pull/16374 (per https://github.com/scylladb/scylladb/issues/16129)
- [ ] require users to first add nodes and then set the replication factor for the DC (per https://github.com/scylladb/scylladb/issues/16129)
- [ ] replace implementaton by having `storage_proxy` reconciling the discrepancy in RF between the `effective_replication_map` and the replication clause (per https://github.com/scylladb/scylladb/issues/16129#issuecomment-1854161578)
- [ ] https://github.com/scylladb/scylladb/issues/19124
- [ ] https://github.com/scylladb/scylladb/issues/19126
- [ ] https://github.com/scylladb/scylladb/issues/19127
- [ ] Shouldn't we skip entering tablet_migration and increasing topology version if ALTER fails? Per https://github.com/scylladb/scylladb/pull/19666#discussion_r1705363625
- [ ] Hardening with more invariant checks, per https://github.com/scylladb/scylladb/issues/20039#issuecomment-2298961796
- [ ] https://github.com/scylladb/scylladb/issues/17572
- [ ] https://github.com/scylladb/scylladb/issues/17579
```
