### ISSUE TITLE
Integrated Backup and Restore in Scylla

### ISSUE THREAD

**Issue by regevran** [scylladb/scylladb#21100]
When this issue is closed Scylla is responsible for backup and restore from S3 object storage.
This is an epic that contains all the sub-issues and PRs in this area.
This is a good way to monitor the progress of this epic.

- [x] #20760 
- [x] #20461 
- [x] #19533 
- [x] https://github.com/scylladb/scylladb/issues/20425
- [x] https://github.com/scylladb/scylladb/issues/20613
- [x] https://github.com/scylladb/scylladb/issues/20868
- [x] https://github.com/scylladb/scylladb/issues/21095
- [x] https://github.com/scylladb/scylladb/issues/20717
- [x] https://github.com/scylladb/scylladb/issues/20716
- [x] https://github.com/scylladb/scylladb/issues/20655
- [x] https://github.com/scylladb/scylladb/issues/20653
- [x] https://github.com/scylladb/scylladb/issues/21099
- [x] https://github.com/scylladb/scylladb/pull/20685
- [x] https://github.com/scylladb/scylladb/issues/20938
- [x] https://github.com/scylladb/scylladb/issues/20373
- [x]  https://github.com/scylladb/scylladb/pull/21054
- [x] https://github.com/scylladb/scylla-monitoring/issues/2103
- [x] https://github.com/scylladb/scylladb/issues/21427
- [x] https://github.com/scylladb/scylladb/pull/23241
- [x] https://github.com/scylladb/scylla-manager/pull/4557

**Comment by mykaul** [comment]
https://github.com/scylladb/scylla-enterprise/issues/4017 is not mandatory for this to be completed.

**Comment by mykaul** [comment]
@regevran - 
https://github.com/scylladb/scylladb/issues/22428 is the largest gap I see, and it's in progress. I hope the performance issues ( https://github.com/scylladb/scylladb/issues/22460 , https://github.com/scylladb/scylladb/issues/22458 ) are also in the works / planned, so we should be good for 2025.2.0 here?

**Comment by regevran** [comment]
#22952 is the last (out of two) PRs to address #22428 - and I think there is not much left to do in it (@robertbindar will be next week back from his PTO and will complete it).
The low throughput PRs #22460 and #22458 are work in progress - I'll try to see if it is possible to take the second-best approach in them (if such exists) and improve to the best approach with future PRs.

**Comment by mykaul** [comment]
@regevran - what's missing from closing this issue for 2025.3?

**Comment by regevran** [comment]
Must be closed:

- [ ] https://github.com/scylladb/scylladb/issues/24419

May be closed, or treated as bugs/enhancements:

- [ ] https://github.com/scylladb/scylladb/issues/24642
- [ ] https://github.com/scylladb/scylladb/issues/24429
- [ ] https://github.com/scylladb/scylladb/issues/24061
- [ ] https://github.com/scylladb/scylladb/issues/23724

**Comment by regevran** [comment]
Also must be resolved:

- [ ] https://github.com/scylladb/scylladb/issues/22707
- [ ] https://github.com/scylladb/scylladb/pull/24793
- [ ] https://github.com/scylladb/scylla-manager/issues/4243

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/pull/24793 is merged, need a backport to 2025.3!

**Comment by mykaul** [comment]
> Must be closed:
> 
> * [ ]  [Query latency raises during native backup #24419](https://github.com/scylladb/scylladb/issues/24419)

@regevran - progress?

**Comment by regevran** [comment]
> @regevran - progress?

https://github.com/scylladb/scylladb/issues/24419 has a few sub-issues - I am waiting for @Michal-Leszczynski to answer https://github.com/scylladb/scylla-manager/issues/4457#issuecomment-3139736469.

**Comment by mykaul** [comment]
This is a release blocker for 2025.4.0. What's missing to complete this?

**Comment by regevran** [comment]
> This is a release blocker for 2025.4.0. What's missing to complete this?

1.
https://github.com/scylladb/scylladb/issues/26025 - `batch-size=0`
I marked this issue as a release blocker.

The problem is not that `--batch-size=0` is requested from SM - rather, this way of running the restore exposes a bug.

2.
https://github.com/scylladb/scylladb/issues/26124 - make sure no throttling during restore

**Comment by bhalevy** [comment]
@regevran are the performance tuning issues really release blockers?

We have 2 serious issues that I'm aware of that cause a failure or a hang that I'm aware of: #22707 and #26483 
Are there other such issues?

**Comment by regevran** [comment]
> Are there other such issues?

Yes. @kreuzerkrieg will file another one once we understand what the problem is. In a nutshell - exceptions (including aborts) are not propagating correctly, or at all.

https://github.com/scylladb/scylladb/issues/22707 - I am waiting with this tablet restore issue, as the low level, s3 client, is still under development, #26483 (although the title suggests it is vNode issue)

**Comment by bhalevy** [comment]
With only a minor enhancement (https://github.com/scylladb/scylladb/issues/24642) left, this no longer blocks the release.

**Comment by dani-tweig** [comment]
@bhalevy , can we close this, and if there is only one minor issue left, handle it separately?

**Comment by bhalevy** [comment]
> [@bhalevy](https://github.com/bhalevy) , can we close this, and if there is only one minor issue left, handle it separately?

Yes, the issues are now managed on Jira
